version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mindflix  # Deployment directory
hooks:
  BeforeInstall:
    - location: scripts/stop-services.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start-services.sh
      timeout: 300
      runas: ec2-user
