version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # For frontend
      python: 3.9  # For backend
    commands:
      - echo "Installing dependencies..."
      - cd mindflix-frontend
      - npm install
      - echo "Frontend dependencies installed."
      - cd ../signup-service
      - pip install -r requirements.txt
      - echo "Signup-service dependencies installed."
      - cd ../video-metadata-service
      - pip install -r requirements.txt
      - echo "Video-metadata-service dependencies installed."
      - cd ../video-streaming-service
      - pip install -r requirements.txt
      - echo "Video-streaming-service dependencies installed."
      - cd ../profile-service
      - pip install -r requirements.txt
      - echo "Profile-service dependencies installed."
  build:
    commands:
      - echo "Running tests for frontend..."
      - cd ../mindflix-frontend
      - npm test -- --watchAll=false
      - echo "Running tests for signup-service..."
      - cd ../signup-service
      - pytest
      - echo "Running tests for video-metadata-service..."
      - cd ../video-metadata-service
      - pytest
      - echo "Running tests for video-streaming-service..."
      - cd ../video-streaming-service
      - pytest
      - echo "Running tests for profile-service..."
      - cd ../profile-service
      - pytest
      - echo "Building frontend..."
      - cd ../mindflix-frontend
      - npm run build
      - echo "Build completed."
  post_build:
    commands:
      - echo "Packaging artifacts for deployment..."
artifacts:
  files:
    - docker-compose.yml                  # Docker Compose configuration
    - mindflix-frontend/build/**/*        # Frontend build output
    - signup-service/**/*                 # Signup service files
    - video-metadata-service/**/*         # Video metadata service files
    - video-streaming-service/**/*        # Video streaming service files
    - profile-service/**/*                # Profile service files
